const { DEFAULT_QUEUE_CONFIG } = require(`../../core/queue/constants`);

const LUA_SCRIPT = `build_match`;
const DEFAULT_CHANNEL_STOP_THRESHOLD = DEFAULT_QUEUE_CONFIG.channelStopThreshold;
const DEFAULT_WARMUP_SECONDS = DEFAULT_QUEUE_CONFIG.matchmakerWarmupSeconds;
const DEFAULT_WARMUP_MAX_POPS_PER_TICK = DEFAULT_QUEUE_CONFIG.matchmakerWarmupMaxPopsPerTick;
const DEFAULT_WARMUP_MIN_SECONDS_BETWEEN_POPS =
	DEFAULT_QUEUE_CONFIG.matchmakerWarmupMinSecondsBetweenPops;
const STATIC_MATCH_SIZE = DEFAULT_QUEUE_CONFIG.matchSize;

module.exports = {
	LUA_SCRIPT,
	DEFAULT_CHANNEL_STOP_THRESHOLD,
	DEFAULT_WARMUP_SECONDS,
	DEFAULT_WARMUP_MAX_POPS_PER_TICK,
	DEFAULT_WARMUP_MIN_SECONDS_BETWEEN_POPS,
	STATIC_MATCH_SIZE,
};
